Return an error instead of panicking
A situation which currently panics is legitimate and so should be diagnosed
using an error. For example under Git Bash on Windows:

riff namespace init ... --manifest file:///C:\somedir\manifest.yaml

currently results in:

panic: readAbsFile called with relative file path: C:somedirmanifest.yaml

because the backslashes are treated as Bash escape characters.

The diagnostics will now be:

Error: Error reading manifest file: absolute path expected instead of relative path: C:somedirmanifest.yaml

Fixes https://github.com/projectriff/riff/issues/1007