Stop wait and show an error when resource ready condition turns false
For example if you create a function without --image and no default
image prefix is set you will see:

```
Created function "my-function"
Error: failed to become ready: missing default image prefix
```

Resolves #1300